# Generated by Django 4.1 on 2022-09-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("formsexemplo", "0002_time_jogador_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricoMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doencas",
                    models.ManyToManyField(blank=True, to="formsexemplo.doenca"),
                ),
                (
                    "jogador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="formsexemplo.jogador",
                    ),
                ),
            ],
        ),
    ]
