# Generated by Django 4.1 on 2022-09-02 17:15

from django.db import migrations, models
import formsexemplo.models


class Migration(migrations.Migration):

    dependencies = [
        ("formsexemplo", "0003_doenca_historicomedico"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogador",
            name="foto",
            field=models.ImageField(
                blank=True,
                upload_to=formsexemplo.models.user_directory_path,
                verbose_name="Foto de perfil",
            ),
        ),
    ]
