# Generated by Django 4.1 on 2022-09-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formsexemplo", "0004_jogador_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogador",
            name="pontos_na_temporada",
            field=models.IntegerField(default=0),
        ),
    ]
