# Generated by Django 4.1 on 2022-09-08 19:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("formsexemplo", "0006_time_fundacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateField(default=datetime.datetime.today)),
                ("final", models.DateField(default=datetime.datetime.today)),
                ("salario", models.FloatField(default=0.0)),
                (
                    "jogador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="formsexemplo.jogador",
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="formsexemplo.time",
                    ),
                ),
            ],
        ),
    ]
