# Generated by Django 4.1 on 2022-09-08 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("formsexemplo", "0007_contrato"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jogador",
            name="time",
        ),
        migrations.AlterField(
            model_name="contrato",
            name="jogador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="contratos",
                to="formsexemplo.jogador",
            ),
        ),
    ]
