# Generated by Django 4.1 on 2022-09-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formsexemplo", "0008_remove_jogador_time_alter_contrato_jogador"),
    ]

    operations = [
        migrations.AddField(
            model_name="time",
            name="plantel",
            field=models.ManyToManyField(
                related_name="times",
                through="formsexemplo.Contrato",
                to="formsexemplo.jogador",
            ),
        ),
    ]
