# Generated by Django 4.1.1 on 2022-09-22 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("formsexemplo", "0009_time_plantel"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
