# Generated by Django 4.1 on 2022-08-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Opcoes",
            new_name="Opcao",
        ),
    ]
