# Generated by Django 4.1 on 2022-08-04 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_rename_opcoes_opcao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opcao",
            name="questao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opcoes",
                to="polls.questao",
            ),
        ),
    ]
